apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
  labels:
    app: url-shortener-boost
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values in production
  DATABASE_PASSWORD: cG9zdGdyZXM=  # postgres
  REDIS_PASSWORD: ""
  CASSANDRA_PASSWORD: Y2Fzc2FuZHJh  # cassandra
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u  # your-super-secret-jwt-key-change-this-in-production
  ADMIN_API_KEY: YWRtaW4tc2VjcmV0LWtleS1jaGFuZ2UtdGhpcw==  # admin-secret-key-change-this
  VIRUS_TOTAL_API_KEY: ""
---
# Note: In production, use external secret management systems like:
# - Kubernetes External Secrets Operator
# - HashiCorp Vault
# - AWS Secrets Manager
# - Azure Key Vault
# - Google Secret Manager