# Prometheus configuration for URL Shortener monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'url-shortener-monitor'
    environment: 'development'

# Rules files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # URL Shortener API
  - job_name: 'url-shortener-api'
    static_configs:
      - targets: ['api:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Kafka metrics (if using kafka_exporter)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 30s

  # Node metrics (if using node_exporter)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Cassandra metrics (if using cassandra_exporter)
  - job_name: 'cassandra'
    static_configs:
      - targets: ['cassandra-exporter:9180']
    scrape_interval: 60s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Remote write (for long-term storage, optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Remote read (for long-term storage, optional)
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint"
#     basic_auth:
#       username: "username"
#       password: "password"

# Service discovery (for Kubernetes deployment)
# kubernetes_sd_configs:
#   - role: pod
#     namespaces:
#       names:
#         - url-shortener
#     selectors:
#       - role: "pod"
#         label: "app=url-shortener-boost"